apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: blue
spec:
  replicas: 3
  selector:
    color: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - image: docker.io/openshift/hello-openshift
        imagePullPolicy: Always
        name: hello
        env:
          - name: RESPONSE
            value: Hello from Blue
      restartPolicy: Always
  triggers:
  - type: ConfigChange
